# Generated by Django 4.2.5 on 2025-09-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='name',
        ),
        migrations.AddField(
            model_name='collaborator',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='remaining_leave_balance',
            field=models.DecimalField(decimal_places=1, default=25.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='used_leave_balance',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
