# Generated by Django 4.2.5 on 2025-10-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='remaining_leave_balance',
            field=models.DecimalField(decimal_places=1, default=32.0, max_digits=5),
        ),
    ]
