# Generated by Django 4.2.5 on 2025-10-01 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_collaborator_name_collaborator_first_name_and_more'),
        ('conges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='EN_COURS', max_length=10)),
                ('nb_jours_demandes', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conges', to='teams.collaborator')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
