# Generated by Django 4.2.5 on 2025-10-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_collaborator_name_collaborator_first_name_and_more'),
        ('conges', '0002_demandeconge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandeconge',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Demande de congé', 'verbose_name_plural': 'Demandes de congé'},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('NOUVELLE_DEMANDE', 'Nouvelle demande'), ('VALIDATION', 'Validation'), ('REFUS', 'Refus'), ('MODIFICATION', 'Modification'), ('ANNULATION', 'Annulation')], default='NOUVELLE_DEMANDE', help_text='Type de notification', max_length=20)),
                ('message', models.TextField(help_text='Message de la notification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de la notification')),
                ('lu', models.BooleanField(default=False, help_text='Indique si la notification a été lue')),
                ('date_lecture', models.DateTimeField(blank=True, help_text='Date de lecture de la notification', null=True)),
                ('demande_conge', models.ForeignKey(help_text='Demande de congé concernée', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='conges.demandeconge')),
                ('manager', models.ForeignKey(help_text='Manager qui recevra la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to='teams.collaborator')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['manager', 'lu'], name='conges_noti_manager_1b07e2_idx'), models.Index(fields=['date_creation'], name='conges_noti_date_cr_83aae0_idx')],
            },
        ),
    ]
