# Generated by Django 4.2.5 on 2025-11-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0004_alter_demandeconge_statut_historiquemodification'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='demi_journee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demandeconge',
            name='nb_jours_demandes',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
